[package]
name = "sp_scanner"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
silentpayments = { git = "https://github.com/cake-tech/rust-silentpayments", branch = "master" }
serde_json = "1.0"

[build-dependencies]
cbindgen = "= 0.24.3"
